apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    provider: mysql
  template:
    metadata:
      labels:
        provider: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: test123
          ports:
          - containerPort: 3306
          volumeMounts:
            - name: var-lib-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: var-lib-mysql
          hostPath:
            path: /data/mysql
