apiVersion: v1
kind: Pod
metadata:
  name: wordpress-proxy
  labels:
    heritage: helm
spec:
  containers:
  - name: wordpress-proxy
    image: gcr.io/google_containers/proxy-to-service:v2
    args: [ "tcp", "80", "wpfrontend.default" ]
    ports:
    - name: http
      protocol: TCP
      containerPort: 80
      hostPort: 80
