apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress
  labels:
    heritage: helm
spec:
  replicas: 1
  selector:
    app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          env:
            - name: WORDPRESS_DB_PASSWORD
              value: test123
          ports:
          - containerPort: 80
            name: http
          volumeMounts:
            - name: var-www-html
              mountPath: /var/www/html
      volumes:
        - name: var-www-html
          hostPath:
            path: /data/wordpress
